@startuml
' Diagrama de Casos de Uso para INASAFE

' Estilo
left to right direction
skinparam packageStyle rect

actor "Usuario" as User

rectangle INASAFE {
  User -- (Autenticarse)
  (Autenticarse) <.. (Registrarse) : extends
  User -- (Gestionar Sesión)
  (Gestionar Sesión) ..> (Cerrar Sesión) : includes

  User -- (Enviar Alerta de Pánico)
  (Enviar Alerta de Pánico) ..> (Obtener Ubicación GPS) : includes

  User -- (Reportar Incidente)

  User -- (Visualizar Mapa)
  (Visualizar Mapa) ..> (Ver Paraderos Cercanos) : includes
  (Visualizar Mapa) ..> (Ver Alertas Activas) : includes
  
  User -- (Consultar Llegada de Micros)
  (Consultar Llegada de Micros) ..> (Calcular Hora de Salida) : includes
  (Consultar Llegada de Micros) ..> (Gestionar Micros Favoritas) : includes

  User -- (Participar en Grupos de Chat)
  (Participar en Grupos de Chat) ..> (Ver Grupos por Paradero) : includes
  (Participar en Grupos de Chat) ..> (Enviar y Recibir Mensajes) : includes
}

@enduml
